# Generated by Django 4.2.6 on 2024-02-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='center_codes',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='classes',
            field=models.CharField(max_length=2),
        ),
    ]
