# Generated by Django 4.2.6 on 2024-02-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_center_codes_alter_student_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='center_codes',
            field=models.CharField(default='', max_length=2),
        ),
    ]
