# Generated by Django 4.2.6 on 2024-02-27 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_roll_no_alter_student_center_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Co_Ordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('Alipurduar', 'Alipurduar'), ('Bankura', 'Bankura'), ('Birbhum', 'Birbhum'), ('Cooch Behar', 'Cooch Behar'), ('Dakshin Dinajpur', 'Dakshin Dinajpur'), ('Darjeeling', 'Darjeeling'), ('Hooghly', 'Hooghly'), ('Howrah', 'Howrah'), ('Jalpaiguri', 'Jalpaiguri'), ('Jhargram', 'Jhargram'), ('Kalimpong', 'Kalimpong'), ('Kolkata', 'Kolkata'), ('Malda', 'Malda'), ('Murshidabad', 'Murshidabad'), ('Nadia', 'Nadia'), ('North 24 Parganas', 'North 24 Parganas'), ('Paschim Bardhaman', 'Paschim Bardhaman'), ('Paschim Medinipur', 'Paschim Medinipur'), ('Purba Bardhaman', 'Purba Bardhaman'), ('Purba Medinipur', 'Purba Medinipur'), ('Purulia', 'Purulia'), ('South 24 Parganas', 'South 24 Parganas'), ('Uttar Dinajpur', 'Uttar Dinajpur')], max_length=20)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
