# Generated by Django 4.2.6 on 2024-03-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_co_ordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co_ordinator',
            name='district',
            field=models.CharField(choices=[('Alipurduar', 'Alipurduar'), ('Bankura', 'Bankura'), ('Birbhum', 'Birbhum'), ('Cooch Behar', 'Cooch Behar'), ('Dakshin Dinajpur', 'Dakshin Dinajpur'), ('Darjeeling', 'Darjeeling'), ('Hooghly', 'Hooghly'), ('Howrah', 'Howrah'), ('Jalpaiguri', 'Jalpaiguri'), ('Jhargram', 'Jhargram'), ('Kalimpong', 'Kalimpong'), ('Kolkata', 'Kolkata'), ('Malda', 'Malda'), ('Murshidabad', 'Murshidabad'), ('Nadia', 'Nadia'), ('North 24 Parganas', ' North 24 Parganas '), ('Paschim Bardhaman', ' Paschim Bardhaman'), ('Paschim Medinipur', 'Paschim Medinipur '), ('Purba Bardhaman', ' Purba Bardhaman'), ('Purba Medinipur', ' Purba Medinipur'), ('Purulia', 'Purulia'), ('South 24 Parganas', 'South 24 Parganas'), ('Uttar Dinajpur', ' Uttar Dinajpur')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='district',
            field=models.CharField(choices=[('Alipurduar', 'Alipurduar'), ('Bankura', 'Bankura'), ('Birbhum', 'Birbhum'), ('Cooch Behar', 'Cooch Behar'), ('Dakshin Dinajpur', 'Dakshin Dinajpur'), ('Darjeeling', 'Darjeeling'), ('Hooghly', 'Hooghly'), ('Howrah', 'Howrah'), ('Jalpaiguri', 'Jalpaiguri'), ('Jhargram', 'Jhargram'), ('Kalimpong', 'Kalimpong'), ('Kolkata', 'Kolkata'), ('Malda', 'Malda'), ('Murshidabad', 'Murshidabad'), ('Nadia', 'Nadia'), ('North 24 Parganas', ' North 24 Parganas '), ('Paschim Bardhaman', ' Paschim Bardhaman'), ('Paschim Medinipur', 'Paschim Medinipur '), ('Purba Bardhaman', ' Purba Bardhaman'), ('Purba Medinipur', ' Purba Medinipur'), ('Purulia', 'Purulia'), ('South 24 Parganas', 'South 24 Parganas'), ('Uttar Dinajpur', ' Uttar Dinajpur')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(default='', max_length=15),
        ),
    ]
