# Generated by Django 4.2.6 on 2024-03-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_co_ordinator_district_alter_student_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
